apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-prediction
  template:
    metadata:
      labels:
        app: weather-prediction
    spec:
      containers:
      - name: weather-prediction
        image: australia-southeast2-docker.pkg.dev/local-concord-457712-v7/weather-prediction/weather-prediction:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: weather-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer