apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-prediction
  template:
    metadata:
      labels:
        app: weather-prediction
    spec:
      containers:
      - name: weather-prediction
        image: us-central1-docker.pkg.dev/mlops-new-447207/weather-prediction/weather-prediction:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: weather-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
