name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: "autopilot-cluster-2"
  GKE_REGION: "australia-southeast2"
  DEPLOYMENT_NAME: "weather-prediction"
  REPOSITORY: "australia-southeast2-docker.pkg.dev/local-concord-457712-v7/weather-prediction"
  IMAGE: "australia-southeast2-docker.pkg.dev/local-concord-457712-v7/weather-prediction/weather-prediction"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Configure Cloud
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth configure-docker australia-southeast2-docker.pkg.dev
          
      - name: Building and Push image
        run: |
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA
          
      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          
      - name: GKE Configuration
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |
          echo "Getting GKE credentials..."
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID
          
          echo "Checking cluster status..."
          gcloud container clusters describe $GKE_CLUSTER --region $GKE_REGION --format="value(status,endpoint)"
          
          echo "Testing kubectl connection with increased timeout..."
          kubectl cluster-info --request-timeout=60s || echo "Direct connection failed, trying alternative approach..."
          
          echo "Attempting to get nodes..."
          kubectl get nodes --request-timeout=60s || echo "Node access failed"
          
      - name: Deploying to Kubernetes
        run: |
          echo "Checking if cluster is accessible..."
          if ! kubectl get nodes --request-timeout=30s; then
            echo "Cluster not directly accessible. Checking cluster status..."
            gcloud container clusters describe $GKE_CLUSTER --region $GKE_REGION --format="value(status)"
            
            echo "Attempting deployment without validation..."
            kubectl apply -f kubernetes-deployments.yaml --validate=false --dry-run=client
            
            echo "If dry-run works, proceeding with actual deployment..."
            kubectl apply -f kubernetes-deployments.yaml --validate=false --timeout=180s
          else
            echo "Cluster is accessible, proceeding with normal deployment..."
            kubectl apply -f kubernetes-deployments.yaml --timeout=120s --validate=false
          fi
          
          echo "Waiting for deployment (with extended timeout)..."
          timeout 300s kubectl rollout status deployment/$DEPLOYMENT_NAME || echo "Rollout status check timed out"
          
          echo "Updating image..."
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA
          
          echo "Final status check..."
          kubectl get deployments -o wide || echo "Failed to get deployment status"
          kubectl get pods -l app=weather-prediction || echo "Failed to get pod status"